language: ruby
script:
  - gem install jekyll bundler
  - bundle install
  - bundle exec rake test
  - bundle exec jekyll build
cache: bundler

- name: Deploy to GitHub Pages
  uses: JamesIves/github-pages-deploy-action@3.5.9
